file(READ "${SOURCE_ROOT}/payload/gamedata/scripts/ild_fix_ui.script" UI)
foreach(FORBIDDEN "io." "os." "time_global(" "start_stop_menu(" "GetHolder(" "SetAutoDelete(true)")
    string(FIND "${UI}" "${FORBIDDEN}" POSITION)
    if(NOT POSITION EQUAL -1)
        message(FATAL_ERROR "Unsupported or unsafe menu API: ${FORBIDDEN}")
    endif()
endforeach()
foreach(REQUIRED "SetAutoDelete(false)" "menu:AttachChild(" "ild_update read " "now + 4000" "heartbeat")
    string(FIND "${UI}" "${REQUIRED}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "Missing update UI lifecycle contract: ${REQUIRED}")
    endif()
endforeach()
# Payload scripts stay ASCII; Cyrillic text must be expressed as CP1251 escapes.
string(REGEX MATCH "[^\t\n -~]" NON_ASCII "${UI}")
if(NOT NON_ASCII STREQUAL "")
    message(FATAL_ERROR "ild_fix_ui.script contains non-ASCII bytes")
endif()
