file(READ "${SOURCE_ROOT}/payload/gamedata/scripts/ild_fix_ui.script" UI)
foreach(FORBIDDEN "io." "os." "time_global(" "start_stop_menu(" "GetHolder(")
    string(FIND "${UI}" "${FORBIDDEN}" POSITION)
    if(NOT POSITION EQUAL -1)
        message(FATAL_ERROR "Unsupported or unsafe menu API: ${FORBIDDEN}")
    endif()
endforeach()
foreach(REQUIRED "SetAutoDelete(true)" "menu:AttachChild(" "ild_update read " "now + 4000")
    string(FIND "${UI}" "${REQUIRED}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "Missing update UI lifecycle contract: ${REQUIRED}")
    endif()
endforeach()
